version: "2"
services:
  api:
    build: ./api
    container_name: api
    ports:
     - "8080:8080"
    links:
      - db:db
      - redis:redis
    depends_on:
     - db
     - redis
    environment:
     - DB_HOST=db
    volumes:
    - ./api:/usr/src/app
  db:
    build: ./db
    container_name: db
    ports:
      - "8083"
  redis:
    image: "redis:latest"
    container_name: redis
