version: "2"
services:
  api:
    build: ./api
    container_name: api
    ports:
     - "8080:8080"
    links:
      - db:db
    depends_on:
     - db
    environment:
     - DB_HOST=db
  db:
    build: ./db
    container_name: db
    ports:
      - "8083"
